### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by datagutten** [Jleagle/gazelle-api-client#4]
How do I call this class?
I have run composer install, but when I require vendor/autoload.php and try to use new Gazelle as in the sample I get a fatal error saying Class 'Gazelle' not found.

**Comment by Jleagle** [comment]
The example does not use the full namespace. Have you tried using:

`$gazelle = new Jleagle\Gazelle\Gazelle(USER, PASS);`

**Comment by datagutten** [comment]
Now 'Jleagle\Helpers\Abstracts\AbstractEnum' is missing

**Comment by Jleagle** [comment]
Closing this, presumably a composer issue or missing imports.
